
name: Deploy to Vapor

on:
  push:
    tags: ['*']

jobs:
  deploy:
    name: Deploy
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: run
      run: |

        echo "$GITHUB_REF_NAME deplyment"
