
name: Deploy to Vapor

on:
  push:
    tags:
    - '*'
jobs:
  deploy:
    name: Deploy
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    env:
          MSG: ${{github.event.message }}
    steps:
    
         - name: Dump GitHub context
           run: echo "tag $GITHUB_REF_NAME	message $MSG"
