
name: Deploy to Vapor

on:
  push:
    tags:        
      - v1.**
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: run
      run: |

        echo "$GITHUB_REF_NAME deplyment"
