
name: Deploy to Vapor

on:
  push:
    tags:
    - '*'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    env:
           GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
         - name: Git checkout
           uses: actions/checkout@v2
           with:
                fetch-depth: '0'
         - name: is belong to master
           run: |
            if [ -z "$(git branch -r --contains $GITHUB_SHA --points-at origin/main)" ] ; then
                echo "failed"   
                exit 1
            else
                echo "pass"
            fi
         - name: Dump GitHub context
           run: echo "$GITHUB_CONTEXT"
