
name: Deploy to Vapor

on:
  push:
    tags:
    - '*'
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    env:
           GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
         - name: Dump GitHub context
           run: echo "$GITHUB_CONTEXT"
