
name: Deploy to Vapor

on:
  push:
    tags:        
      - v1.**
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
         - name: Dump GitHub context
           env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
           run: echo "$GITHUB_CONTEXT"
